name: PHP run

on:
  workflow_dispatch:
  schedule:
  - cron: "0 */8 * * *"

permissions:
  contents: read

jobs:
  update:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Make converter.php executable
      run: chmod +x converter.php
    - name: Use r-a-y converter
      run: php ./converter.php


