name: PHP run

on:
  workflow_dispatch:
  schedule:
  - cron: "0 */8 * * *"

permissions:
  contents: read

jobs:
  update:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Make converter.php executable
      run: chmod +x converter.php
    - name: Use r-a-y converter
      run: php ./converter.php

    - name: Verified commit
    # You may pin to the exact commit or the version.
    # uses: swinton/commit@bfa68d879ec57187f2c5bf616158433763f05f06
    uses: swinton/commit@v2.0.0
    with:
      # Newline-separated list of files to be committed, relative to root of repository.

      files: 
      # Base directory containing files to be committed, defaults to the GitHub workspace directory path, $GITHUB_WORKSPACE.

      workspace: # optional, default is 
      # Commit message to be used

      commit-message: 
      # Reference to be updated with commit. This reference must already exist. Defaults to the repository's default branch ref.

      ref: # optional, default is 

