name: PHP run

on:
  workflow_dispatch:
  schedule:
  - cron: "0 */8 * * *"

permissions:
  contents: read

jobs:
  update:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Make converter.php executable
      run: chmod +x converter.php
    - name: Use r-a-y converter
      run: php ./converter.php
      
    - name: Commit files
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -a -m "Add changes"
      
    - name: GitHub Push
  # You may pin to the exact commit or the version.
  # uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6
      uses: ad-m/github-push-action@v0.6.0

