name: Update blocklist

on:
  workflow_dispatch:
  schedule:
  - cron: "0 */6 * * *"

permissions:
  contents: write

jobs:
  update:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Make converter.php executable
      run: chmod +x converter.php
    - name: Use r-a-y converter
      run: php ./converter.php
      
#    - name: Commit files
#      run: |
#        git config --local user.email "github-actions[bot]@users.noreply.github.com"
#        git config --local user.name "github-actions[bot]"
#        git commit -a -m "Add changes"
      
    - name: Git Commit/Push Changes
      uses: actions-x/commit@v6
      with:
        email: github-actions[bot]@users.noreply.github.com
        name: github-actions[bot]

  convert:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4

    - run: npm i -g @adguard/hostlist-compiler
    - run: hostlist-compiler -c hostlist-compiler.json -o adguardDNS-r-a-y.txt
    
    - name: Git Commit/Push Changes
      uses: actions-x/commit@v6
      with:
        email: github-actions[bot]@users.noreply.github.com
        name: github-actions[bot]

